Add tests to show BufRead can be used after decoding
rust-lang/flate2-rs pull request #402
Opened 2024-04-23 18:42 UTC by jongiddy

Copy the test from `gzip::bufread` to demonstrate that it also works for `zlib` and `deflate`.

This demonstrates that #401 works with `bufread` decoders.

2024-04-24 05:07 UTC, Byron approved these changes
That's a great idea, and a very valid expectation on top of that.
Thank you!

2024-04-24 05:09 UTC, Byron requested changes
Actually, I just realized that these tests should be on integration level (i.e. in `tests/`), they don't use internal APIs (and shouldn't have to).
Thank you.

2024-04-25 06:02 UTC, jongiddy commented
I put the tests here for symmetry with the equivalent gzip tests, which are also currently unit tests. While unit tests can access private items, I've never heard that unit tests **must** access private items. And, due to the additional build costs of integration tests, I tend to prefer unit tests where possible.

Nevertheless, I can move the tests to the integration level. Should I move the equivalent gzip tests too?

2024-04-25 06:46 UTC, Byron commented
> I put the tests here for symmetry with the equivalent gzip tests, which are also currently unit tests.

Apologies, I wasn't aware and didn't want to change the way things are done here. It seems integration tests have a specific purpose (here, making use of fixtures) and unit-tests are used for everything else. Let's keep it that way.

2024-04-25 06:47 UTC, Byron approved these changes

2024-04-25 06:47 UTC, merged