Check minimal version of Rust that compiles
rust-lang/flate2-rs pull request #421
Opened 2024-08-16 06:56 UTC by jongiddy

Specify a minimum version of the Rust compiler that successfully builds the crate. This allows us to be aware if the minimal version increases and to avoid issues such as https://github.com/rust-lang/flate2-rs/issues/370

The minimum version is a best-effort measured value and is different to the MSRV which is a support guarantee. The minimum version can be incremented by a PR in order to pass tests, as long as the MSRV holds. When the minimum version increases, the next release should be a minor version, to allow any affected users to pin to a previous minor version.

2024-08-16 07:29 UTC, jongiddy commented
The minimum version for the updated `miniz_oxide` is higher than I expected. Since the `rust-version` in `Cargo.toml` can prevent Cargo from selecting the crate, it needs to be the minimum version supported by a common feature-set. We do not want to prevent someone using Rust 1.56.1 from downloading the crate if they are planning to use `zlib-*` feature.

My current thinking is to remove the `rust-version` directive from `Cargo.toml` but keep the test, and use it to document behavior. (e.g. if using Rust < 1.60 a different backend must be selected).

2024-08-16 20:37 UTC, jongiddy commented
Ah it's `ppv-lite86` which is a transitive dependency in the dev-dependencies. v0.2.17 in my lock file has no dependencies, but the latest v0.2.20 used in GitHub Actions adds `zerocopy` which requires 1.60.
```
[dev-dependencies]
├── quickcheck v1.0.3
│   └── rand v0.8.5
│       ├── libc v0.2.153
│       ├── rand_chacha v0.3.1
│       │   ├── ppv-lite86 v0.2.17
```

2024-08-16 21:21 UTC, jongiddy commented
Changed the CI workflow to only test that code builds, without running the tests.

2024-08-17 17:43 UTC, Byron requested changes
Thanks a lot for making clearer the defacto way the MSRV was handled.

I'd also hope that adding the `rust-version` can't break anyone. In theory, those who use  even more ancient compiler versions will benefit from those not respecting that field yet. So it should be safe especially with a value as low as that.

There is just one improvement that I think could be made to the MSRV paragraph, which would have helped me to understand it more quickly.

2024-08-17 17:43 UTC, Byron commented on README.md
> +The `Cargo.toml` file specifies a minimum version for which builds passed at some point.
```suggestion
The `Cargo.toml` file specifies a minimum version for which builds passed at some point using the `rust-version` field.
```

2024-08-17 17:43 UTC, Byron commented on README.md
> +The `Cargo.toml` file specifies a minimum version for which builds passed at some point.
Since 'minimum version' is really the `rust-version` field, I wonder if that name should rather be used to reduce the level of abstraction.

2024-08-18 08:39 UTC, Byron approved these changes
Thanks a lot!

2024-08-18 08:40 UTC, merged

2024-08-18 08:51 UTC, Byron commented on .github/workflows/main.yml
> +        build: [stable, beta, nightly, minimal, macos, windows, mingw]
CI now fails [on `main`](https://github.com/rust-lang/flate2-rs/actions/runs/10439240311), and I have a feeling that this entry might be the cause of it?

It's surprising that it didn't fail CI before.

In any case, your help for a fix will be welcome.

2024-08-18 09:31 UTC, jongiddy commented
Oh wow, CI should complain more noisily if that happens!